const SIXTY_SECONDS = 60;
const ONE_SECOND = 1;
const TEN_SECONDS = 10;
const FIVE_MINUTES_IN_SECONDS = 300;
const DEFAULT_MINUTE = "25";
const DEFAULT_SECOND = "00";

export {
  SIXTY_SECONDS,
  ONE_SECOND,
  TEN_SECONDS,
  FIVE_MINUTES_IN_SECONDS,
  DEFAULT_MINUTE,
  DEFAULT_SECOND,
};